package com.strataspent.app.ui.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential

/**
 * Wraps the Credential Manager + Sign in with Google handshake.
 *
 * Returns a Google ID token on success that the caller can hand to
 * [com.strataspent.app.data.AuthRepository.signInWithGoogleIdToken].
 *
 * The [serverClientId] must be the **Web** OAuth client ID generated by the
 * Firebase project (Project Settings → Your apps → Web SDK config). When the
 * `google-services` Gradle plugin is applied, this ID is exposed as
 * `R.string.default_web_client_id`.
 */
class GoogleSignInLauncher(
    private val serverClientId: String,
    private val context: Context,
) {

    sealed interface Result {
        data class Success(val idToken: String) : Result
        data object Cancelled : Result
        data class Error(val message: String) : Result
    }

    suspend fun launch(): Result {
        return try {
            val cm = CredentialManager.create(context)
            val option = GetSignInWithGoogleOption.Builder(serverClientId).build()
            val request = GetCredentialRequest.Builder()
                .addCredentialOption(option)
                .build()
            val response = cm.getCredential(context, request)
            val credential = response.credential
            if (credential is CustomCredential &&
                credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
            ) {
                val google = GoogleIdTokenCredential.createFrom(credential.data)
                Result.Success(google.idToken)
            } else {
                Result.Error("Unexpected credential type: ${credential.type}")
            }
        } catch (_: GetCredentialCancellationException) {
            Result.Cancelled
        } catch (e: NoCredentialException) {
            Result.Error(e.message ?: "No Google account available on this device")
        } catch (e: GetCredentialException) {
            Result.Error(e.message ?: "Sign-in failed")
        } catch (t: Throwable) {
            Result.Error(t.message ?: "Sign-in failed")
        }
    }
}
